DZ1_Button_Accordion
js-tasks-ru/htmlcss-20220919_mangecu pull request #3
Opened 2022-10-31 10:06 UTC by Mangecu

2022-10-31 10:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-31 22:54 UTC, GSemikozov requested changes

2022-10-31 22:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.preview__line {
если описываем компонент - то здесь должны быть стили / классы только этого компонента, и никаких других.

2022-10-31 22:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.preview__line + .button {
это можно при желании реализовать на уровне блока  .preview - .preview__line + .preview__button. Но скорее это вообще просто вспомогательные стили чтобы разместить кнопки по сетке - так вот этого делать как раз и не надо)

2022-10-31 22:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button {
класс блока - тут все общие стили. Так что - не хватает паддингов, border-radius, height и font-family

2022-10-31 22:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button + .button {
лишнее, марджины на уровне блока не задаем

2022-10-31 22:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
эти стили - скорректированные - должны размещаться в классе блока, а не в классе элемент другого блока

2022-10-31 22:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.preview__button_primary {
button_primary

2022-10-31 22:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.preview__button_secondary {
button_secondary

2022-10-31 22:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.preview__button_alternate {
button_alternate

2022-10-31 22:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.preview__button:disabled {
button:disabled + pointer-events: none + opacity: 0.5

2022-10-31 22:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.preview__button:disabled {
и ниже фиксы по аналогии

2022-11-07 07:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-07 07:39 UTC, Mangecu commented on 03-lection1/01-button/button.css
> +.button {
Данное замечание поправил. Но вопрос есть. Как бы цвет, бордер-радиус,  транзишн прикручены к этим кнопкам. Вразве эти свойства не относятся к свойствам-состояния? Как бы если да, то я должен по бэм их прикрутить не к блоку, а к модификатору. Поправь меня, пожалуйста, если я что-то не правильно понял

2022-11-07 07:40 UTC, Mangecu commented on 03-lection1/01-button/button.css
> +    width: 189px;
В ходе исправления ошибок, получилось так, что `.preview__button`  был удалён из-за не надобности.

2022-11-11 06:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-11-11 11:52 UTC, GSemikozov requested changes

2022-11-11 11:52 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
жестко не фиксируем, ширина должна зависеть от внутреннего содержимого)

2022-11-11 11:52 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 14px 0 13px;
слева-справа тоже надо (в контексте коммента ниже)

2022-11-11 11:52 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border: 1px solid #4263EB;
можно описывать только то что реально меняется, то есть border-color

2022-11-11 11:52 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border: 1px solid var(--purple);
и тут

2022-11-11 11:52 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border: 1px solid var(--grey-3);
и тут

2022-11-11 11:52 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_primary-hover:hover {
.button_primary:hover

2022-11-11 11:52 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_secondary-hover:hover {
.button_secondary:hover

2022-11-11 11:52 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_alternate-hover:hover {
.button_alternate:hover

2022-11-11 11:52 UTC, GSemikozov commented on components/preview/preview.css
> +    background-color: #F9FAFC;
если превью-бордер, тогда фон сюда не надо, пусть фон будет на .preview)

2022-11-17 07:53 UTC, Mangecu commented on 03-lection1/01-button/button.css
> +    width: 189px;
Убрал жесткую фиксацию. Прописал левый и правый паддинги для каждой кнопки, потому что не пойму, если прописывать одинаковые паддинги по краям то какой брать? Понимаю что в макете по сетке сделано, для лучшего восприятия.

2022-11-17 07:53 UTC, Mangecu commented on 03-lection1/01-button/button.css
> +    padding: 14px 0 13px;
Это приписал в комменте выше=)

2022-11-18 09:50 UTC, Mangecu commented on 03-lection1/01-button/button.css
> +    border: 1px solid #4263EB;
Убрал лишнее. Оставил только то что меняется при наведении. Единственное не понятно почему рамка button_alternate не плавно меняется при наведении. Если можешь, объясни пожалуйста, как сделать плавный переход.

2022-11-18 09:50 UTC, Mangecu commented on 03-lection1/01-button/button.css
> +    border: 1px solid var(--purple);
И тут сделал)

2022-11-18 09:51 UTC, Mangecu commented on 03-lection1/01-button/button.css
> +    border: 1px solid var(--grey-3);
И тут сделал

2022-11-18 09:51 UTC, Mangecu commented on 03-lection1/01-button/button.css
> +.button_primary-hover:hover {
Переписал

2022-11-18 09:51 UTC, Mangecu commented on 03-lection1/01-button/button.css
> +.button_secondary-hover:hover {
Переписал

2022-11-18 09:51 UTC, Mangecu commented on 03-lection1/01-button/button.css
> +.button_alternate-hover:hover {
Переписал

2022-11-18 09:53 UTC, Mangecu commented on components/preview/preview.css
> +    background-color: #F9FAFC;
Относительно той разметки которая была (классы просто переименовал), если я прописываю фон в `.preview`, то у меня закрашивается только контейнер, а по макету на всю ширину экрана краситься фон. Вот.

2022-11-18 09:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-18 11:04 UTC, GSemikozov requested changes

2022-11-18 11:04 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding-left: 66.42px;
паддинги одинаковые и задаются на уровне .button

2022-11-18 11:04 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding-left: 56.04px;
и тут

2022-11-18 11:04 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border: 1px solid var(--grey-3);
тут не сделано - паддинги удвлить, а написать border-color: var(--grey-3)

2022-11-18 11:04 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 14px 0 13px;
`padding: 15px 15px 14px`

2022-11-18 11:04 UTC, GSemikozov commented on components/preview/preview.css
> +    background-color: #F9FAFC;
сейчас preview - это дочерний элемент page, page растягивается на всю ширину, а значит и main (.preview) тоже

2022-11-20 16:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-21 20:49 UTC, GSemikozov requested changes

2022-11-21 20:49 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button:nth-child(3n) {
нет, так делать ни в коем случае нельзя! Мы здесь верстаем Кнопку, а не то, как эту кнопку можно выстраивать по сетке в каком-либо контексте (тем более что при такой записи где бы в коде мы ни находились, везде это правило будет применяться, что крайне не гибко!)

2022-11-21 20:49 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button:nth-child(3n) {
чтобы не менять паддинги alternate, нужно задать box-sizing: border-box. Если нет - тогда указать эти паддинги на .button_alternate

2022-11-23 10:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-24 21:41 UTC, GSemikozov approved these changes

2022-11-24 21:41 UTC, merged