DZ5 Checkbox Radio Toggler Tab
js-tasks-ru/htmlcss-20220919_mangecu pull request #9
Opened 2023-02-18 14:14 UTC by Mangecu

2023-02-18 14:14 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-19 21:06 UTC, GSemikozov requested changes

2023-02-19 21:06 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +        background-size: cover;
и тогда это свойство здесь и ниже нет смысла дублировать

2023-02-19 21:06 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +        background: url('./public/forest_768.jpg') center;
просто background-image

2023-02-19 21:06 UTC, GSemikozov commented on components/container/container.css
> +        max-width: 343px;
лишнее (достаточно просто паддинги по краям добавить )

2023-02-19 21:06 UTC, GSemikozov commented on 06-lection4/01-avatar/index.html
> +   <header class="header header__main">
элемента блока одновременно свой собственный элемент (папа одновременно при этом свой собственный ребенок)? так не бывает ;) просьба исправить аналогичные места ниже. Если нет смысла использовать отдельные элементы - то значит стили нужно перенести в классы блоков.

2023-02-21 08:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-21 08:29 UTC, Mangecu commented on 06-lection4/02-background-image/background-image.css
> +        background-size: cover;
Решил через `background-image`, `background-size: cover` и `background-position: center`, но без повторений

2023-02-21 08:30 UTC, Mangecu commented on components/container/container.css
> +        max-width: 343px;
Сделал. Как понял, `padding` хватит, при маленьких размерах вьюпорта. Если не правильно понял, поправь, пожалуйста

2023-02-21 08:31 UTC, Mangecu commented on 06-lection4/01-avatar/index.html
> +   <header class="header header__main">
Поправил везде. Но пришлось создать ещё один div. Если применил не хорошую практику, поправь меня пожалуйста. Просто другого выхода я не знаю...

2023-02-27 13:18 UTC, GSemikozov requested changes

2023-02-27 13:18 UTC, GSemikozov commented on 06-lection4/01-avatar/index.html
> +   <header class="header header__main">
до сих пор не исправлено. Нужно удалить header__main если это элемент блока и использовать отдельно внутри блока, либо если это модификатор - то оформить как header_main

2023-03-02 14:16 UTC, GSemikozov approved these changes

2023-03-02 14:17 UTC, merged